Solution/Old/ordermggt/adminsite/Controllers/UserLoginController.cs
using adminsite.Models;
using adminsite.Models.DTO;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.UI;

namespace adminsite.Controllers
{
    [OutputCache(NoStore = true, Duration = 0, Location = OutputCacheLocation.None)]
    public class UserLoginController : Controller
    {
        //
        // GET: /UserLogin/
        private OrderManagmentEntities db = new OrderManagmentEntities();

        public void setData()
        {
            ViewBag.type = db.TblTypeMasters.ToList<TblTypeMaster>();

        }

        public ActionResult Index()
        {
            return View();
        }



        // [HttpGet]
        //public ActionResult Userlogin()
        //{
        //    setData();
        //    return View();
        //}
        //[HttpPost]
        //public ActionResult Userlogin(TblUserLoginMaster Model)
        //{
        //    if (ModelState.IsValid)
        //    {
        //        setData();

        //        db.TblUserLoginMasters.Add(Model);
        //        db.SaveChanges();



        //        if (Model.TypeID == 1)
        //        {
        //            Session["UserName"] = Model.UserName;
        //            Session["Password"] = Model.Password;
        //            Session["UserID"] = Model.UserID;

        //        }
        //        else if (Model.TypeID == 2)
        //        {
        //            Session["UserName"] = Model.UserName;
        //            Session["Password"] = Model.Password;
        //            Session["UserID"] = Model.UserID;
        //            return RedirectToAction("CreateCustomer", "Customer");
        //        }
        //        else
        //        {
        //            return View(Model);
        //        }

        //    }
        //    return RedirectToAction("CreateSupplier", "Supplier");    
        //}


        [HttpGet]
        public ActionResult UserReg()
        {
            setData();
            return View();
        }
        [HttpPost]
        public ActionResult UserReg(TblUserLoginMaster Model)
        {
            setData();
            var check = db.TblUserLoginMasters.Where(h => h.UserName == Model.UserName).FirstOrDefault();

            if (check == null)
            {
                if (ModelState.IsValid)
                {
                    Model.IsActive = true;
                    Model.CreatedBy = int.Parse(Session["AdminName"].ToString());
                    Model.CreatedDateTime = DateTime.Now;
                    db.TblUserLoginMasters.Add(Model);
                    db.SaveChanges();
                    ViewBag.actionmsg = "1";
                    if (Model.TypeID == 1)
                    {
                        Session["UserName"] = Model.UserName;
                        Session["Password"] = Model.Password;
                        Session["UserID"] = Model.UserID;
                        return RedirectToAction("CreateSupplier", "Supplier");
                    }
                    else if (Model.TypeID == 2)
                    {
                        Session["UserName"] = Model.UserName;
                        Session["Password"] = Model.Password;
                        Session["UserID"] = Model.UserID;
                        return RedirectToAction("CreateCustomer", "Customer");
                    }
                    else
                    {
                        return View(Model);
                    }
                }
                return View(Model);
            }
            else
            {
                ViewBag.actionmsg = "0";
                ViewBag.userNAME = check.UserName;
                return View(Model);
            }

        }





    }
}

Solution/Old/ordermggt/adminsite/Views/UserLogin/UserReg.cshtml
@model adminsite.Models.TblUserLoginMaster
@{
    ViewBag.Title = "UserReg";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


@using (Html.BeginForm("UserReg", "UserLogin", FormMethod.Post, new { @class = "form-horizontal" }))
{
 <div id="page-content">
        <div class="row">
            <div class="col-sm-12">
                <div class="panel">
                    <div class="panel-heading">
                        <h3 class="panel-title">User </h3>
                    </div>

                    <div class="panel-body">
                       

                        <div class="form-group">
                            <label class="col-sm-3 control-label">User Name(Mobile no)</label>
                            <div class="col-md-6 col-sm-6">
                                @Html.TextBoxFor(Model => Model.UserName, new { @class = "form-control", @placeholder = "Supplier MobileNo /customer MobileNo" , @maxlength="10" , @minlength="10",autocomplete = "off"})
                                @Html.ValidationMessageFor(Model => Model.UserName)
                            </div>
                        </div>



                        <div class="form-group">
                            <label class="col-sm-3 control-label">Password</label>
                            <div class="col-md-6 col-sm-6">
                                   @Html.PasswordFor(Model => Model.Password, new { @class = "form-control", @placeholder = "Password" , @maxlength="10" , @minlength="3",autocomplete = "off"})
                                   @Html.ValidationMessageFor(Model => Model.Password)
                            </div>
                        </div>


                         <div class="form-group">
                            <label class="col-sm-3 control-label">User Type</label>
                            <div class="col-md-6 col-sm-6">
                              @Html.DropDownListFor(Model => Model.TypeID, new SelectList(ViewBag.type, "TypeID", "TypeName"), "---Select User Type  ---", new { @class = "form-control" })
                                @Html.ValidationMessageFor(Model => Model.TypeID)
                            </div>
                        </div>
                        
                       
                            <div class="row">
                                <div class="col-sm-3"></div>
                                <div class="col-sm-6">
                                    <button class="btn btn-info btn-labeled fa fa-thumbs-o-up" type="submit">Submit</button>
                                </div>
                            </div>
                      

                    </div>
                </div>
            </div>


        </div>


    </div>
}


<div class="row">
    <div class="pad-ver">
        <div class="col-sm-3"></div>
        <div class="col-sm-6">
            @if (ViewBag.actionmsg == "1")
            {
                <label class="control-label  btn btn-success btn-labeled  fa fa-thumbs-o-up">Well done! Your data is Successfully Inserted</label>
            }
            @if (ViewBag.actionmsg == "0")
            { 
                <label class="control-label btn btn-danger btn-labeled fa fa-thumbs-o-down">"  @ViewBag.userNAME "  Name is already Exist.  .............</label>
            }
        </div>
    </div>
</div>